FROM python:3.11

# Install system dependencies
RUN apt-get update && apt-get install -y \
    postgresql-client \
    libxml2-dev \
    libxslt1-dev \
    libldap2-dev \
    libsasl2-dev \
    libpq-dev \
    libjpeg-dev \
    libpng-dev \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY . /app

RUN pip install --upgrade pip \
    && pip install --no-cache-dir -r requirements.txt

EXPOSE 10000

CMD ["python", "odoo/odoo-bin", "-c", "odoo.conf"]
